workflows:
  android-apk:
    name: Build Android APK

    environment:
      node: 20
      java: 17

    scripts:
      - npm install
      - npm run build
      - npm install @capacitor/core @capacitor/cli @capacitor/android
      - npx cap sync android
      - cd android
      - chmod +x gradlew
      - ./gradlew assembleDebug

    artifacts:
      - android/app/build/outputs/apk/debug/app-debug.apk