workflows:
  android-apk:
    name: Build Android APK

    environment:
      node: 22
      java: 17

    triggering:
      events:
        - push
        - pull_request

    scripts:
      - npm ci
      - npm run build
      - npx cap sync android

      # Vérification des fichiers
      - pwd
      - ls -la
      - ls -la android

      # Compilation Android
      - cd android
      - ls -la
      - ./gradlew assembleDebug

    artifacts:
      - android/app/build/outputs/apk/debug/app-debug.apk