workflows:
  android-apk:
    name: Android APK

    environment:
      node: 22
      java: 17

    scripts:
      - echo "=== DOSSIER COURANT ==="
      - pwd
      - ls -la
      - ls -la android

      - npm install
      - npm run build

      - npx cap sync android

      - cd android

      - echo "=== CONTENU ANDROID ==="
      - pwd
      - ls -la

      - ./gradlew assembleDebug

    artifacts:
      - android/app/build/outputs/apk/debug/app-debug.apk